apiVersion: v1
kind: page
spec:
  id: DLDNAol
  title: SlugTestsas
  display: standalone
  layout: container
  slug: [slug-test/:cat, slug-test/:cat/:id, slug-test/te:teId, slug-test]
  content:
    - component: Stack
      name: stack
      props:
        justifyContent: start
      children:
        - component: Text
          name: slug1
          props:
            value: Page Slug is
        - component: Text
          name: slug
          props:
            value:
              $$jsExpression: |
                JSON.stringify(page.parameters.pageParams)
        - component: Text
          name: slug2
          props:
            value:
              $$jsExpression: |
                page.parameters.pageParams.cat
  queries:
    - name: query
      mode: mutation
      query:
        function: getURL.ts#default
        kind: local
