apiVersion: v1
kind: page
spec:
  id: LiHp-Yw
  title: ShellContainer
  display: shell
  content:
    - component: Paper
      name: paper
      props:
        sx:
          background: '#CCC'
          width: 300px
      children:
        - component: Rating
          name: rating1
          layout:
            horizontalAlign: center
            verticalAlign: end
      layout:
        verticalAlign: end
    - component: Container
      name: container
      props:
        visible: false
        sx: {}
      children:
        - component: Button
          name: button
    - component: Container
      name: container1
    - component: ButtonGroup
      name: buttonGroup
      props:
        visible: true
        size: small
        variant: outlined
        color: primary
      children:
        - component: Button
          name: button1
          props:
            size: small
            variant: contained
        - component: Button
          name: button2
          props:
            size: small
            color: secondary
            variant: outlined
        - component: Button
          name: button4
          props:
            size: small
            color: secondary
            variant: outlined
    - component: Container
      name: container2
    - component: ButtonGroup
      name: buttonGroup1
      props:
        fullWidth: false
        disabled: false
        orientation: horizontal
        size: medium
        color: primary
        variant: contained
        disableElevation: true
      children:
        - component: Button
          name: button3
          props:
            size: small
            color: primary
            variant: contained
    - component: Button
      name: button5
    - component: Select
      name: select
      props:
        options:
          - asd
          - dsa
    - component: RadioGroup
      name: radio
      props:
        options:
          - Deneme
          - Test
          - Hey hey hey
          - sasd
        orientation: horizontal
        label: Test
        name: Deneme
        isRequired: false
        isInvalid: false
        defaultValue: Test
    - component: Rating
      name: rating
      props:
        max: 10
        emptyIcon: TurnedInNot
        value: 1
        icon: TurnedIn
        precision: 0.5
        readOnly: false
        onChange:
          $$jsExpressionAction: paper.elevation=5
      layout:
        horizontalAlign: center
        verticalAlign: center
    - component: TextField
      name: textField
    - component: Autocomplete
      name: autocomplete
  slug: [shell-container]
