apiVersion: v1
kind: page
spec:
  id: T7t5AlB
  title: page
  display: standalone
  layout: container
  slug:
    - page
  content:
    - component: Button
      name: button1
      props:
        onClick:
          $$navigationAction:
            page: VL1vLQx
            pageSlug: profile
            parameters: {}
            slugParameters:
              id:
                $$jsExpression: ''
              action:
                $$jsExpression: |
                  'asd'
    - component: PageRenderer
      name: pageRenderer
      props:
        value: page#E4tRpZL
    - component: Text
      name: text
    # - page: VL1vLQx
