apiVersion: v1
kind: page
spec:
  id: 4BcBLLv
  title: Page
  display: standalone
  layout: container
  slug:
    - page
  content:
    - component: Button
      name: button
      props:
        onClick:
          $$navigationAction:
            page: VL1vLQx
            pageSlug: page2:id
            parameters: {}
            slugParameters:
              id: dsasd
  parameters:
    - name: b
      value: ''
