apiVersion: v1
kind: page
spec:
  id: T7t5AlB
  title: page
  display: standalone
  layout: fluid
  slug:
    - page
  content:
    - component: Button
      name: button1
      props:
        onClick:
          $$navigationAction:
            page: VL1vLQx
            slug: profile-:id/:action
            pageSlug: profile-:id/:action
            parameters:
              a: a1
              b: b1
            slugParameters:
              '0': profile
              '1': profile-:id
              '2': profile-:id/:action
              id: '123'
              action: asd
